#! /bin/sh

sxhkd &
$HOME/.config/bspwm/scripts/monitores.sh &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
wal -R -n &
eww daemon &
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1 &
discord &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor VGA-0 -d VI VII VIII IX X
$HOME/.config/polybar/Xsapo/launch.sh &

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding 	    44

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color7"
bspc config presel_feedback_color "$color0"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^6'
bspc rule -a Roberto state=floating
